# Generated by Django 2.2.7 on 2021-01-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Math_Marks', models.IntegerField()),
                ('Physics_Marks', models.IntegerField()),
                ('Chemistry_Marks', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Per', models.IntegerField()),
            ],
        ),
    ]
