# Generated by Django 3.0.1 on 2021-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210108_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
