# Generated by Django 3.0.1 on 2021-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210307_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='art_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('English_Marks', models.IntegerField()),
                ('Hindi_Marks', models.IntegerField()),
                ('Geography_Marks', models.IntegerField()),
                ('History', models.IntegerField()),
                ('Civics', models.IntegerField()),
                ('Sociology', models.IntegerField()),
                ('Psychology', models.IntegerField()),
                ('Political_science', models.IntegerField()),
                ('Mathematics', models.IntegerField()),
                ('Sanskrit', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='commerce_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Accountancy_Marks', models.IntegerField()),
                ('Business_Studies_Marks', models.IntegerField()),
                ('Economics_Marks', models.IntegerField()),
                ('Mathematics', models.IntegerField()),
                ('English_Marks', models.IntegerField()),
                ('Hindi_Marks', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sci_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Mathematics_Marks', models.IntegerField()),
                ('Physics_Marks', models.IntegerField()),
                ('Chemistry_Marks', models.IntegerField()),
                ('Biology_Marks', models.IntegerField()),
                ('Computer_Science_Marks', models.IntegerField()),
                ('English_Marks', models.IntegerField()),
                ('Hindi_Marks', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Per', models.FloatField()),
            ],
        ),
    ]
