# Generated by Django 3.0.1 on 2021-03-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_art_marks_commerce_marks_sci_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_marks',
            old_name='Civics',
            new_name='Civics_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='History',
            new_name='History_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='Mathematics',
            new_name='Mathematics_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='Political_science',
            new_name='Political_science_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='Psychology',
            new_name='Psychology_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='Sanskrit',
            new_name='Sanskrit_Marks',
        ),
        migrations.RenameField(
            model_name='art_marks',
            old_name='Sociology',
            new_name='Sociology_Marks',
        ),
        migrations.RenameField(
            model_name='commerce_marks',
            old_name='Mathematics',
            new_name='Mathematics_Marks',
        ),
        migrations.RenameField(
            model_name='sci_marks',
            old_name='Computer_Science_Marks',
            new_name='Computer_Marks',
        ),
    ]
