# Generated by Django 3.0.1 on 2021-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_sci_marks_op_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sci_marks',
            name='Biology_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sci_marks',
            name='Computer_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sci_marks',
            name='Mathematics_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
