# Generated by Django 3.0.1 on 2021-03-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210309_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sci_marks',
            name='op_subject',
        ),
    ]
