# Generated by Django 3.0.1 on 2021-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_sci_marks_op_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_marks',
            name='Civics_Marks',
        ),
        migrations.RemoveField(
            model_name='art_marks',
            name='Mathematics_Marks',
        ),
        migrations.RemoveField(
            model_name='art_marks',
            name='Psychology_Marks',
        ),
        migrations.AlterField(
            model_name='art_marks',
            name='English_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='art_marks',
            name='Hindi_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='art_marks',
            name='Sanskrit_Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
